// <auto-generated />
using APIDAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDAL.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20251223045624_creating book table")]
    partial class creatingbooktable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIDAL.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCode")
                        .IsUnique()
                        .HasFilter("[BookCode] IS NOT NULL");

                    b.HasIndex("BookName")
                        .IsUnique()
                        .HasFilter("[BookName] IS NOT NULL");

                    b.ToTable("tbl_books");
                });
#pragma warning restore 612, 618
        }
    }
}
